name: Version Management

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
      custom_version:
        description: 'Or specify custom version (e.g., 4.3.0) - overrides type'
        required: false
        type: string

jobs:
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Bump version
        run: |
          if [ -n "${{ github.event.inputs.custom_version }}" ]; then
            echo "Using custom version: ${{ github.event.inputs.custom_version }}"
            npm version ${{ github.event.inputs.custom_version }} --no-git-tag-version
          else
            echo "Using version type: ${{ github.event.inputs.version_type }}"
            npm version ${{ github.event.inputs.version_type }} --no-git-tag-version
          fi
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "🔢 New version: $VERSION"
          
      - name: Update CHANGELOG
        run: |
          DATE=$(date +%Y-%m-%d)
          sed -i "3i\\
\\
## [${{ env.VERSION }}] - $DATE\\
\\
### Changed\\
\\
- Version bump\\
" CHANGELOG.md
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: bump version to ${{ env.VERSION }}"
          title: "chore: bump version to ${{ env.VERSION }}"
          body: |
            Automated version bump to ${{ env.VERSION }}
            
            This PR will trigger automatic publishing to GitHub Packages when merged.
          branch: version-bump-${{ env.VERSION }}
          delete-branch: true